# PostgreSQL is the default database for the models and so.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Websockets uses Solid Cable with SQLite in production.
sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development: &development
  <<: *default
  host: <%= Rails.application.credentials.dig(:db_dev, :host) %>
  port: <%= Rails.application.credentials.dig(:db_dev, :port) || 5432 %>
  username: <%= Rails.application.credentials.dig(:db_dev, :user) %>
  password: <%= Rails.application.credentials.dig(:db_dev, :passwd) %>
  database: <%= Rails.application.credentials.dig(:db_dev, :name) %>

test:
  <<: *development

production: &production
  <<: *default
  host: <%= Rails.application.credentials.dig(:db_prod, :host) %>
  port: <%= Rails.application.credentials.dig(:db_prod, :port) || 5432 %>
  username: <%= Rails.application.credentials.dig(:db_prod, :user) %>
  password: <%= Rails.application.credentials.dig(:db_prod, :passwd) %>
  database: <%= Rails.application.credentials.dig(:db_prod, :name) %>

cable:
  <<: *sqlite
  database: storage/cable.sqlite3
  migrations_paths: db/cable_migrate
